name: pills_guardian_v2_rebuild_complete
description: Aplicación para gestionar fórmulas médicas, recordatorios y estadísticas de medicamentos escaneados.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  google_mlkit_text_recognition: ^0.15.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  image_picker: ^1.0.7
  appwrite: ^16.0.0
  fl_chart: ^0.66.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

dependency_overrides:
  flutter_web_auth_2: null
  flutter_web_auth_2_platform_interface: null
